### ISSUE TITLE
Swagger UI inputs "api_key" and "Auth header" are gone

### ISSUE THREAD

**Issue by alex-pl** [smoketurner/dropwizard-swagger#71] opened 2017-02-23 14:22 UTC
The Swagger UI inputs for "api_key" and "Auth header" were gone recently in my installations. 

**Current Behavior:**
<img width="1008" alt="bildschirmfoto 2017-02-23 um 14 04 32" src="https://cloud.githubusercontent.com/assets/4785458/23260562/b6848ca6-f9d2-11e6-802f-caf835fd5d18.png">

**Expected Behavior:**
![bildschirmfoto 2017-02-23 um 14 13 10](https://cloud.githubusercontent.com/assets/4785458/23260561/b6849ca0-f9d2-11e6-9b39-05045dd41a4c.png)

I've checked the available dropwizard-swagger versions. The fields are available up to version `1.0.0-1` and hidden starting at version `1.0.5-1`.

I tried to add the following values in my `config.yml`, but they didn't help:
```yaml
swagger:
  swaggerViewConfiguration:
    showAuth: true
    showApiSelector: true
```

Am I missing something or is it a bug?

**Comment by jplock** [comment] 2017-02-23 18:47
Duplicate of https://github.com/smoketurner/dropwizard-swagger/issues/66

**Closed by jplock** 2017-02-23 18:47 UTC

**Comment by alex-pl** [comment] 2017-02-23 18:51
Sorry, I was blind 🙈. Thanks!
